---
- name: install kibana
  hosts: kibana
  become: yes

  tasks:
  
  - name: import the elastic apt key
    ansible.builtin.apt_key:
      url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
      state: present

  - name: install elastic repository
    ansible.builtin.apt_repository:
      repo: deb https://mirror.yandex.ru/mirrors/elastic/8/ stable main
      state: present

  - name: update cache repository
    ansible.builtin.apt:
      update_cache: yes

  - name: install packages
    ansible.builtin.apt:
      name:
        - apt-transport-https
        - openjdk-8-jre-headless
        - kibana
      state: present
      
  - name: setting kibana
    ansible.builtin.lineinfile:
      path: /etc/kibana/kibana.yml
      regexp: '^#server.host: "localhost"'
      line: "server.host: 0.0.0.0"

  - name: enable and restart kibana
    ansible.builtin.systemd:
      name: kibana
      enabled: true
      daemon_reload: true
      masked: no
      state: started
...